name: PHP Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v2
    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: /tmp/composer-cache
        key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
    - uses: php-actions/composer@v6
      with:
        php_version: 8.1
    - name: PHP CS Fixer
      run: vendor/bin/php-cs-fixer fix --dry-run -v --show-progress none
    - name: PHPStan
      run: vendor/bin/phpstan analyze --memory-limit=1G --no-ansi --no-progress
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
